image: atlassian/default-image:3

pipelines:
  # Automated pipeline for syncing Bitbucket repository with its GitHub based on tags, ensuring real-time updates across platforms for releases
  tags:
    '*':
      - step:
          name: Sync GitHub On New Tag
          image: alpine/git:latest
          clone:
            depth: full
          script:
            - git clone --bare git@bitbucket.org:ku-gdsc/docker.git docker
            - cd docker
            - git push git@github.com:ku-gdsc/docker.git main:main --follow-tags
